from src.load import load_data
from src.preprocess import clean_data
from src.denoise import denoise, calculate_snr
from src.pca import apply_pca
from src.visualization import make_rgb, make_false_color, save_images

import matplotlib.pyplot as plt
import numpy as np
import os
import boto3
import datetime


# S3 bucket where input .nc files and output results are stored
BUCKET_NAME = "hyperspectral-data-koushik"


# =========================
# S3 DOWNLOAD
# =========================
def download_input(filename):
    """
    Download a NetCDF input file from the S3 'input/' prefix to local 'data/' directory.

    Args:
        filename (str): Name of the .nc file to download (e.g., 'sample.nc').

    Returns:
        str: Local file path where the file was saved.

    Raises:
        Exception: Re-raises any S3 download error after logging it.
    """
    s3 = boto3.client("s3")
    local_path = f"data/{filename}"

    try:
        print(f"[INFO] Downloading {filename} from S3...")
        s3.download_file(
            BUCKET_NAME,
            f"input/{filename}",  # S3 key under the 'input/' prefix
            local_path            # Local destination path
        )
        return local_path

    except Exception as e:
        print("[ERROR] S3 download failed:", e)
        raise


# =========================
# S3 UPLOAD
# =========================
def upload_outputs(output_prefix):
    """
    Upload all pipeline output files to S3 under a timestamped prefix.

    Args:
        output_prefix (str): S3 key prefix for this run (e.g., 'output/sample_20250101_120000').
    """
    s3 = boto3.client("s3")

    # List of all expected output files generated by the pipeline
    files = [
        "rgb.png",
        "false_color.png",
        "pca.png",
        "denoise_comparison.png",
        "snr.txt"
    ]

    for file in files:
        try:
            s3.upload_file(
                f"outputs/{file}",          # Local source path
                BUCKET_NAME,                # Target S3 bucket
                f"{output_prefix}/{file}"   # S3 destination key
            )
            print(f"[INFO] Uploaded {file}")

        except Exception as e:
            # Log failure but continue uploading remaining files
            print(f"[ERROR] Failed to upload {file}: {e}")


# =========================
# VISUALIZATION HELPERS
# =========================
def compare_denoising(original, denoised):
    """
    Generate and save a side-by-side comparison of one band before and after denoising.

    Uses band 50 by default, or the last available band if fewer than 50 exist.

    Args:
        original (np.ndarray): Raw 3D hyperspectral array (rows, cols, bands).
        denoised (np.ndarray): Denoised 3D array of the same shape.
    """
    # Pick band 50 for comparison, or the last band if data has fewer than 50 bands
    band = min(50, original.shape[2] - 1)

    plt.figure(figsize=(10, 5))

    plt.subplot(1, 2, 1)
    plt.imshow(original[:, :, band], cmap="gray")
    plt.title("Original")
    plt.axis("off")

    plt.subplot(1, 2, 2)
    plt.imshow(denoised[:, :, band], cmap="gray")
    plt.title("Denoised")
    plt.axis("off")

    plt.tight_layout()
    plt.savefig("outputs/denoise_comparison.png", dpi=150)
    plt.close()  # Free memory after saving


def save_pca_image(pca_result):
    """
    Normalize and save the first PCA component as a grayscale image.

    The first principal component captures the most variance in the data
    and serves as a compact spectral summary. Percentile-based normalization
    (2nd–98th) clips outliers before scaling to [0, 1] for display.

    Args:
        pca_result (np.ndarray): 3D PCA output array (rows, cols, components).
    """
    # Extract first principal component (highest variance)
    pca_img = pca_result[:, :, 0]

    # Compute 2nd and 98th percentiles to clip extreme outliers
    p2 = np.nanpercentile(pca_img, 2)
    p98 = np.nanpercentile(pca_img, 98)

    # Normalize to [0, 1] range; small epsilon (1e-6) prevents division by zero
    pca_img = np.clip(
        (pca_img - p2) / (p98 - p2 + 1e-6),
        0,
        1
    )

    plt.imsave("outputs/pca.png", pca_img, cmap="gray")


# =========================
# MAIN PIPELINE
# =========================
def run_pipeline(filename="sample.nc"):
    """
    Execute the full hyperspectral image processing pipeline end-to-end.

    Steps:
        1. Download input .nc file from S3
        2. Load and clean radiance data
        3. Denoise using Gaussian filtering
        4. Compute SNR and noise improvement metrics
        5. Apply PCA for dimensionality reduction
        6. Generate RGB, false color, PCA, and denoising visualizations
        7. Upload all outputs to S3 under a timestamped prefix
        8. Clean up local input file

    Args:
        filename (str): Name of the NetCDF file in S3 'input/' prefix. Default is 'sample.nc'.

    Returns:
        dict: Pipeline metrics and S3 output path with keys:
              'snr', 'noise_before', 'noise_after', 'improvement', 's3_output_path'.
    """

    # Ensure local output and data directories exist before writing
    os.makedirs("outputs", exist_ok=True)
    os.makedirs("data", exist_ok=True)

    # Build a timestamped S3 output prefix to avoid overwriting previous runs
    base_name = os.path.splitext(filename)[0]
    timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")

    output_prefix = f"output/{base_name}_{timestamp}"

    print("[INFO] Starting pipeline...")

    # -------------------------
    # Download Input
    # -------------------------
    local_file = download_input(filename)

    # -------------------------
    # Load & Clean
    # -------------------------
    print("[INFO] Loading data...")
    data = load_data(local_file)

    print("[INFO] Cleaning data...")
    # Replace physically invalid (negative) radiance values with NaN
    data = clean_data(data)

    # -------------------------
    # Denoising
    # -------------------------
    print("[INFO] Denoising...")
    denoised = denoise(data)

    # -------------------------
    # Metrics
    # -------------------------
    print("[INFO] Calculating SNR...")
    snr = calculate_snr(data, denoised)

    # Measure noise as std of raw data vs. residual (original - denoised)
    noise_before = np.nanstd(data)
    noise_after = np.nanstd(data - denoised)

    # Percentage reduction in noise as a result of denoising
    improvement = (
        (noise_before - noise_after) / noise_before
    ) * 100

    print(f"[INFO] SNR: {snr}")
    print(f"[INFO] Noise Before: {noise_before:.2f}")
    print(f"[INFO] Noise After: {noise_after:.2f}")
    print(f"[INFO] Improvement: {improvement:.2f}%")

    # Persist metrics to a text file for upload alongside visual outputs
    with open("outputs/snr.txt", "w") as f:
        f.write(f"SNR: {snr}\n")
        f.write(f"Noise Before: {noise_before:.2f}\n")
        f.write(f"Noise After: {noise_after:.2f}\n")
        f.write(f"Improvement: {improvement:.2f}%\n")

    # -------------------------
    # PCA
    # -------------------------
    print("[INFO] Applying PCA...")
    # Reduce spectral dimensionality; first component captures most variance
    pca_result = apply_pca(denoised)

    # -------------------------
    # Visualizations
    # -------------------------
    print("[INFO] Generating RGB & False Color...")
    rgb = make_rgb(denoised)
    fc = make_false_color(denoised)

    save_images(rgb, fc)

    print("[INFO] Saving PCA image...")
    save_pca_image(pca_result)

    print("[INFO] Saving denoise comparison...")
    compare_denoising(data, denoised)

    # -------------------------
    # Upload Results
    # -------------------------
    print("[INFO] Uploading results to S3...")
    upload_outputs(output_prefix)

    # -------------------------
    # Cleanup Local File
    # -------------------------
    # Remove the downloaded .nc file to free disk space after processing
    if os.path.exists(local_file):
        os.remove(local_file)

    print("[INFO] Pipeline completed ✅")

    return {
        "snr": float(snr),
        "noise_before": float(noise_before),
        "noise_after": float(noise_after),
        "improvement": float(improvement),
        "s3_output_path": output_prefix
    }


if __name__ == "__main__":
    run_pipeline()